# Generated by Django 2.0.3 on 2020-05-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='special',
        ),
        migrations.RemoveField(
            model_name='sicillianpizza',
            name='special',
        ),
    ]
