# Generated by Django 2.0.3 on 2020-05-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200502_0628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='sicillianpizza',
            name='size',
        ),
    ]
