# Generated by Django 2.0.3 on 2020-05-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200502_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='size',
            field=models.CharField(choices=[('1', 'Small'), ('2', 'Large')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='sicillianpizza',
            name='size',
            field=models.CharField(choices=[('1', 'Small'), ('2', 'Large')], default='1', max_length=20),
        ),
    ]
