# Generated by Django 2.0.3 on 2020-05-06 06:55

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_title',
        ),
        migrations.AddField(
            model_name='cart',
            name='extras',
            field=models.CharField(default='1', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(choices=[('1', 'RP'), ('2', 'SP'), ('3', 'S'), ('4', 'Pa'), ('5', 'Sa'), ('6', 'DP')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default='1'),
        ),
    ]
