# Generated by Django 2.0.3 on 2020-05-06 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200506_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='size',
            new_name='product_id',
        ),
    ]
