# Generated by Django 2.0.3 on 2020-05-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='extras',
        ),
        migrations.AddField(
            model_name='cart',
            name='extras',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
    ]
