# Generated by Django 2.0.3 on 2020-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200507_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.IntegerField(choices=[('1', 'RP'), ('2', 'SP'), ('3', 'S'), ('4', 'Pa'), ('5', 'Sa'), ('6', 'DP')], default='1'),
        ),
    ]
