# Generated by Django 2.0.3 on 2020-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.IntegerField(choices=[('0', 0), ('1', 1), ('2', 2)], default='1'),
        ),
    ]
