# Generated by Django 2.0.3 on 2020-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200507_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Complete')], default='1', max_length=20),
        ),
    ]
