# Generated by Django 2.0.3 on 2020-05-11 07:33

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200511_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='extras',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
